### ISSUE TITLE
Backfill audio

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/meetings#14]
We'll need to backfill audio recordings from the beginning of 2020 til whenever we automate audio as part of github actions

**Comment by kimdhamilton** [comment]
See also #15

**Comment by vsnt** [comment]
Was this covered in the work on the minutes in the community issues list @kimdhamilton ?

**Comment by kimdhamilton** [comment]
which one was that?

**Comment by vsnt** [comment]
https://github.com/w3c-ccg/community/issues/123 @kimdhamilton

**Comment by kimdhamilton** [comment]
yes, that should cover it
