### ISSUE TITLE
Fix CCG minutes.

### ISSUE THREAD

**Issue by davidlehn** [w3c-ccg/meetings#84]
The main CCG meeting minutes from 2022-09-20 onward are not correct.  The irc logs are there, but the generated and sent emails and the web pages are wrong and usually just have one line.  The other related groups seem fine.

https://github.com/w3c-ccg/meetings/tree/main/2022-09-20
https://github.com/w3c-ccg/meetings/tree/main/2022-09-27
https://github.com/w3c-ccg/meetings/tree/main/2022-10-04
https://github.com/w3c-ccg/meetings/tree/main/2022-10-11
https://github.com/w3c-ccg/meetings/tree/main/2022-10-18
https://github.com/w3c-ccg/meetings/tree/main/2022-10-25
https://github.com/w3c-ccg/meetings/tree/main/2022-11-01

**Comment by brownoxford** [comment]
At first glance, this appears to be a line-ending issue in `irc.log`. Investigating.

**Comment by brownoxford** [comment]
These have been fixed, please review and confirm.

**Comment by davidlehn** [comment]
- Looks much better, thanks!
- The agenda search links are kind of weird, but that's fine.
- I saw an updated 2022-09-20 minutes mail went out.  Were the other updated ones supposed to get mailed out too?
- Was it a line-end issue?  I see the logs were converted.  Did the tooling get fixed to handle this in the future?

**Comment by brownoxford** [comment]
I *believe* that [this is the offending line](https://github.com/w3c-ccg/meetings/blob/main/scribe-tool/scrawl.js#L874), will try for a PR today.
