### ISSUE TITLE
Twitter CI action failing

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c-ccg/meetings#86]
Getting the following error when attempting to generate VC-Edu meeting minutes:

![image](https://github.com/w3c-ccg/meetings/assets/947005/75417500-a5d1-48c3-ab33-8bcca8fc47b5)

The Twitter notification CI step is failing, because I don't have correct credentials, or something.
Do we /need/ a Twitter CI step?

**Comment by dmitrizagidulin** [comment]
Ohhhh I suspect this probably has to do with Twitter (now 'X') disabling their API access. We should remove that step.

**Comment by aljones15** [comment]
They switched to a paid API in Feb 9 https://twitter.com/XDevelopers/status/1621026986784337922

But what is odd that the [X Developer platform](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api) still lists a free API with a limit of 1500 tweets per month. 
Regardless with all the changes at X/Twitter might be better to disable and await what comes next.
